package com.granatum.core.infrastructure.database.entities

import com.granatum.core.domain.type.TipoOperacionFichaje
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes
import java.time.Instant
import java.util.UUID

/**
 * APPEND-ONLY record of one received operation. The evidentiary record of the
 * working-time register, and the idempotency mechanism for the mobile app's
 * deferred operations.
 *
 * **Every field is `val`.** Immutability starts in the type, not in a
 * convention someone has to remember: there is no setter to call by accident.
 * There is no `updatedAt` either, because there is nothing to update.
 *
 * Deliberately has no JPA association to [EmpleadoEntity] or [FichajeEntity],
 * only their ids: nothing must be able to cascade a delete into this table.
 */
@Entity
@Table(name = "fichaje_eventos")
class FichajeEventoEntity(
    @Id
    val id: UUID = UUID.randomUUID(),

    /** Idempotency key generated by the client. Unique. */
    @Column(name = "client_event_id", nullable = false, unique = true)
    val clientEventId: UUID,

    @Column(name = "empleado_id", nullable = false)
    val empleadoId: UUID,

    @Column(name = "fichaje_id")
    val fichajeId: UUID? = null,

    @Enumerated(EnumType.STRING)
    @Column(name = "tipo_operacion", nullable = false, length = 15)
    val tipoOperacion: TipoOperacionFichaje,

    /** When it actually happened, per the device. Drives the computation. */
    @Column(name = "occurred_at", nullable = false)
    val occurredAt: Instant,

    /** When it reached the server. Recorded, never used for computation. */
    @Column(name = "received_at", nullable = false)
    val receivedAt: Instant,

    /**
     * SHA-256 of the canonicalised request body. The same key arriving with a
     * different body means the client reused an idempotency key for another
     * operation; that must surface as a conflict rather than silently returning
     * some other operation's result.
     */
    @Column(name = "huella_peticion", nullable = false, length = 64)
    val huellaPeticion: String,

    @Column(name = "estado_respuesta", nullable = false)
    val estadoRespuesta: Int,

    /**
     * The original response, returned verbatim on a resend. Stored rather than
     * recomputed: returning current state would give a different answer if the
     * shift moved on between the first send and the retry, which is precisely
     * the case this exists for.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "cuerpo_respuesta", nullable = false)
    val cuerpoRespuesta: String
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is FichajeEventoEntity) return false
        return id == other.id
    }

    override fun hashCode(): Int = javaClass.hashCode()

    /** No response body and no ids beyond its own: both may carry personal detail. */
    override fun toString(): String =
        "FichajeEventoEntity(id=$id, tipoOperacion=$tipoOperacion)"
}
