-- APPEND-ONLY. The evidentiary record of the working-time register, and the
-- idempotency mechanism for the mobile app's deferred operations. Serves both
-- at no extra cost: the table is needed for idempotency regardless, so using it
-- as the immutable proof is free.
--
-- Never UPDATEd, never DELETEd inside the retention period. No updated_at
-- column, deliberately: there is nothing to update.
--
-- No foreign keys to empleados or fichajes, also deliberately: nothing must be
-- able to cascade a delete into the immutable table.
CREATE TABLE fichaje_eventos (
    id                UUID         PRIMARY KEY,
    -- Idempotency key generated by the client. A resend with this same id and
    -- the same body returns the stored response verbatim.
    client_event_id   UUID         NOT NULL,
    empleado_id       UUID         NOT NULL,
    fichaje_id        UUID,
    tipo_operacion    VARCHAR(15)  NOT NULL,
    -- When it actually happened, per the device. This is what the working-time
    -- computation uses.
    occurred_at       TIMESTAMPTZ  NOT NULL,
    -- When it reached the server. Kept separately; never used for computation.
    received_at       TIMESTAMPTZ  NOT NULL,
    -- SHA-256 of the canonicalised request body. Same key with a different body
    -- means the client reused an idempotency key for another operation, which
    -- is a client bug and must surface as 409 rather than silently returning
    -- some other operation's response.
    huella_peticion   VARCHAR(64)  NOT NULL,
    estado_respuesta  INTEGER      NOT NULL,
    cuerpo_respuesta  JSONB        NOT NULL,
    CONSTRAINT uk_fichaje_eventos_client_event_id UNIQUE (client_event_id),
    CONSTRAINT ck_fichaje_eventos_tipo_operacion
        CHECK (tipo_operacion IN ('ENTRADA', 'INICIO_PAUSA', 'FIN_PAUSA', 'SALIDA'))
);

CREATE INDEX idx_fichaje_eventos_fichaje ON fichaje_eventos (fichaje_id);
CREATE INDEX idx_fichaje_eventos_occurred ON fichaje_eventos (empleado_id, occurred_at);

ALTER TABLE fichaje_eventos ENABLE ROW LEVEL SECURITY;
